
    - name: Disable nodejs default version
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable Nodejs 20 version
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: Install Nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present7yhb

    - name: Add expense user
      ansible.builtin.user:
        name: expense

    - name: Copy backend service
      ansible.builtin.template:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Import app_prereq
      ansible.builtin.import_role:
        name: common
        tasks_from: app-prereq

    - name: Install packages based on package.json
      community.general.npm:
        path: /app

    - name: Install Mysql client and PyMysql Python module # Required for mysql_db ansible module
      ansible.builtin.dnf:
        name:
          - mysql
          - python3.11-PyMySQL+rsa
        state: present

    - name: Load Schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: "{{ secrets.MYSQL_USER }}"
        login_password: "{{ secrets.MYSQL_PASS }}"
        login_host: mysql-{{env}}.sdevopsp25.site

    - name: Start Backend Service
      ansible.builtin.service:
        name: backend
        state: restarted
        enabled: true
        daemon_reload: true