    - name : Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Copy Expense conf file
      ansible.builtin.template:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Import app_prereq
      ansible.builtin.import_role:
        name: common
        tasks_from: app-prereq

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
