    - name: install mysql
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: start mysql
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: true

    - name: Setting root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.MYSQL_PASS }}
