component: backend
app_path: /app
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret={{env}}/data/backend token={{vault_token}} url=http://vault.sdevopsp25.site:8200 validate_certs=false') }}"